#!/bin/bash

NAME=$(dialog --backtitle "User Creation" \
    --inputbox "Please enter the name of the user you'd like to create:" 10 100 3>&1 1>&2 2>&3)

if [[ $NAME == "" ]]; then
    echo "Failure"
    /ssh_hub/scripts/main_menu.sh
    exit 500
fi

usehub=false
if dialog --backtitle "User Creation" \
    --yesno "Would you like this user to use the Hub System?" 10 100; then
    mkdir -p /ssh_hub/keys
    ssh-keygen -b 2048 -t rsa -f /ssh_hub/keys/$NAME -q -N ""
    chmod a+rx /ssh_hub/keys/$NAME
    PUB_KEY_NODE=$(cat /ssh_hub/keys/$NAME.pub)
    usehub=true
fi

PUB_KEY=$(dialog --backtitle "User Creation" \
    --inputbox "Enter a Public Key generated by the User (If no hub, for general auth. If hub, for hub auth.)" 10 100 3>&1 1>&2 2>&3)

if [[ $PUB_KEY == "" ]]; then
    echo "Failure"
    rm -rf /ssh_hub/keys/$NAME
    rm -rf /ssh_hub/keys/$NAME.pub
    exit 500
fi

clear
pass=$(echo $RANDOM | md5sum | head -c 16)

if [[ $usehub == true ]]; then
    echo "- Create User (HUB)"
    useradd $NAME
    echo "- Apply PUB Key (HUB)"
    mkdir -p /home/$NAME
    cd /home/$NAME/
    mkdir -p .ssh
    cd .ssh
    echo $PUB_KEY > authorized_keys
    echo "- Changing Permissions (HUB)"
    chown $NAME:$NAME /home/$NAME/.ssh
    chmod 700 /home/$NAME/.ssh
    chown $NAME:$NAME /home/$NAME/.ssh/authorized_keys
    chmod 600 /home/$NAME/.ssh/authorized_keys
    echo "- Gen Password (HUB)"
    echo "$NAME:$pass" | chpasswd
    echo "- Changing Shell (HUB)"
    chsh $NAME -s /ssh_hub/shells/hub_user.shell
    echo "- Restart SSHD"
    systemctl restart sshd
    echo ""
    echo " --- HUB COMPLETE --- "
    echo ""
fi

echo "- Create User (BACKEND)"
# Execute the command on each remote system using SSH
for remote_system in "${REMOTE_SYSTEMS[@]}"; do
    ssh "$remote_system" "useradd $NAME"
done

echo "- Apply PUB Key (BACKEND)"
# Execute the command on each remote system using SSH
for remote_system in "${REMOTE_SYSTEMS[@]}"; do
    ssh "$remote_system" "mkdir -p /home/$NAME/.ssh"
done

if [[ $usehub == true ]]; then
    # Execute the command on each remote system using SSH
    for remote_system in "${REMOTE_SYSTEMS[@]}"; do
        ssh "$remote_system" "rsync -avz /ssh_hub/keys/$NAME.pub /home/$NAME/.ssh/authorized_keys"
    done
else
    # Execute the command on each remote system using SSH
    for remote_system in "${REMOTE_SYSTEMS[@]}"; do
        ssh "$remote_system" "echo $PUB_KEY > /home/$NAME/.ssh/authorized_keys"
    done
fi

echo "- Gen Password (BACKEND)"
# Execute the command on each remote system using SSH
for remote_system in "${REMOTE_SYSTEMS[@]}"; do
    ssh "$remote_system" "echo '$pass\n$pass' | passwd $NAME"
done

dialog --backtitle "User Creation" \
    --msgbox "Done!" 10 100

/ssh_hub/scripts/main_menu.sh
exit 500
